### ISSUE TITLE
is_dir() expects parameter 1 to be a valid path, array 

### ISSUE THREAD

**Issue by binsarjr** [rakit/blade#1]

**Comment by emsifa** [comment]
Ini udah solved ya?

**Comment by binsarjr** [comment]
iya mas,ternyata ad yg salah,dan btw mas klo blade kan ad cache nya,nah klo
saya menerapkan fitur auto clean cache blade apakah akan aman ?

Pada tanggal Min, 17 Feb 2019 12.13, Muhammad Syifa <
notifications@github.com> menulis:

**Comment by emsifa** [comment]
Harusnya sih aman, soalnya kalau file cachenya nggak ada, blade akan generate lagi.

**Comment by binsarjr** [comment]
ok terima kasih,soalnya klo gk bikin fitur auto clean cache pasti numpuk
smpahnya,btw blum buka forum forum gtu mas buat membahas sputar karya mas
sendiri

Pada tanggal Min, 17 Feb 2019 12.58, Muhammad Syifa <
notifications@github.com> menulis:

**Comment by BinsarJr** [comment]
Hai,

Saya baru saja menandatangani petisi "@poldakalbar_, Segera Berikan
Keadilan untuk Audrey #JusticeForAudrey!" dan ingin tahu apakah Anda dapat
membantu dengan menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 4.500.000 tanda tangan dan kami
membutuhkan dukungan lebih banyak. Anda dapat membaca lebih banyak petisi
dan menandatanganinya di sini:

http://chng.it/nSmYL8YPgM

Terima kasih!
Binsar
